bert:
  path: 'bert-base-multilingual-cased'

data:
  source: '.en'
  target: '.hyp'
  marking: '.ann'
  raw: 'data/dummy'
  train: 'data/dummy.tok'

train:
  lr: 0.003
  optimizer: Adam
  batch_size: 32
  epochs: 10
