bert:
  path: 'bert-base-german-dbmdz-cased'

data:
  source: '.en'
  target: '.hyp'
  marking: '.ann'
  raw_train: 'data/markings'
  train: 'data/markings.tok'
  raw_dev: 'data/user_mark'
  dev: 'data/user_mark.tok'

model:
  hidden_dimension: 100
  activation: "tanh"
  freeze_bert: False
  head_bias: False

train:
  bert_lr: 0.000003
  lr: 0.0003
  optimizer: adam
  batch_size: 32
  epochs: 25
  seed: 41
  model_dir: humanmt_de
  shuffle: True
  cuda: True
  early_stopping_metric: 'eval_metric'
  overwrite: True
  normalization: tokens
  bad_weight: 5.0
  validation_freq: 100
  logging_freq: 10
  weighting: 'wrong'
  eval_batch_size: 128
  eval_metric: 'f1_prod' # f1_1, f1_0, acc, f1_prod

generate:
  batch_size: 2
